spring.application.name=friends-auto-mobile

spring.datasource.url=jdbc:mysql://localhost:3306/friends_auto_mobile
spring.datasource.username=root
spring.datasource.password=1437

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080